# src/weighted_cardinality_estimation/__init__.pyi
from typing import List

class ExpSketch:
    def __init__(self, m: int, seeds: List[int]) -> None: ...
    def add(self, x: str, weight: float = ...) -> None: ...
    def estimate(self) -> float: ...
    def jaccard_struct(self, other: "ExpSketch") -> float: ...

class FastExpSketch:
    def __init__(self, m: int, seeds: List[int]) -> None: ...
    def add(self, x: str, weight: float = ...) -> None: ...
    def estimate(self) -> float: ...
    def jaccard_struct(self, other: "FastExpSketch") -> float: ...
